
export const ExerciseConstans = {
    SET_MUSCLES: 'SET_MUSCLES',
    SELECT_EXERCISE: 'SELECT_EXERCISE',
    CREATE_EXERCISE: 'CREATE_EXERCISE',
    DELETE_EXERCISE: 'DELETE_EXERCISE',
    SET_TOTAL_EXERCISES: 'SET_TOTAL_EXERCISES',
    SET_SELECTED_EXERCISES: 'SET_SELECTED_EXERCISES',
    SET_EDIT_FORM: 'SET_EDIT_FORM',
    SHOW_EDIT: 'SHOW_EDIT' 
}